package org.jgc.herbarium.be;
// Generated 03/10/2016 12:07:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Casillero generated by hbm2java
 */
@Component
public class Casillero  implements java.io.Serializable {


     private Long idcasillero;
     private Gabinete gabinete;
     private Integer numero;
     private String descripcion;
     private Boolean estado;
     private Set ejemplars = new HashSet(0);
     

     public Casillero() {
        this.idcasillero = null;
        this.gabinete = new Gabinete();
    }

	
    public Casillero(Gabinete gabinete) {
        this.gabinete = gabinete;
    }
    public Casillero(Gabinete gabinete, Integer numero, String descripcion, Boolean estado, Set ejemplars) {
       this.gabinete = gabinete;
       this.numero = numero;
       this.descripcion = descripcion;
       this.estado = estado;
       this.ejemplars = ejemplars;
    }
   
    public Long getIdcasillero() {
        return this.idcasillero;
    }
    
    public void setIdcasillero(Long idcasillero) {
        this.idcasillero = idcasillero;
    }
    public Gabinete getGabinete() {
        return this.gabinete;
    }
    
    public void setGabinete(Gabinete gabinete) {
        this.gabinete = gabinete;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getEjemplars() {
        return this.ejemplars;
    }
    
    public void setEjemplars(Set ejemplars) {
        this.ejemplars = ejemplars;
    }




}


