package org.jgc.herbarium.be;
// Generated 03/10/2016 12:07:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Departamento generated by hbm2java
 */
@Component
public class Departamento  implements java.io.Serializable {


     private Long iddepartamento;
     private int codDepartamento;
     private String denominacion;
     private Set provincias = new HashSet(0);

    public Departamento() {
    }
    
    public Departamento(int codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public Departamento(int codDepartamento, String denominacion, Set provincias) {
       this.codDepartamento = codDepartamento;
       this.denominacion = denominacion;
       this.provincias = provincias;
    }
   
    public Long getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(Long iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public int getCodDepartamento() {
        return this.codDepartamento;
    }
    
    public void setCodDepartamento(int codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public Set getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set provincias) {
        this.provincias = provincias;
    }




}


