package org.jgc.herbarium.be;
// Generated 03/10/2016 12:07:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Especie generated by hbm2java
 */
@Component
public class Especie  implements java.io.Serializable {


     private Long idespecie;
     private Genero genero;
     private Habito habito;
     private String denominacion;
     private String autor;
     private String nombreVulgar1;
     private String nombreVulgar2;
     private String nombreVulgar3;
     private String descripcion;
     private Boolean estado;
     private Set colectas = new HashSet(0);

    public Especie() {        
        this.idespecie = null;
        this.genero = new Genero();
    }

	
    public Especie(Genero genero) {
        this.genero = genero;
    }
    public Especie(Genero genero, Habito habito, String denominacion, String autor, String nombreVulgar1, String nombreVulgar2, String nombreVulgar3, String descripcion, Boolean estado, Set colectas) {
       this.genero = genero;
       this.habito = habito;
       this.denominacion = denominacion;
       this.autor = autor;
       this.nombreVulgar1 = nombreVulgar1;
       this.nombreVulgar2 = nombreVulgar2;
       this.nombreVulgar3 = nombreVulgar3;
       this.descripcion = descripcion;
       this.estado = estado;
       this.colectas = colectas;
    }
   
    public Long getIdespecie() {
        return this.idespecie;
    }
    
    public void setIdespecie(Long idespecie) {
        this.idespecie = idespecie;
    }
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }
    public Habito getHabito() {
        return this.habito;
    }
    
    public void setHabito(Habito habito) {
        this.habito = habito;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getNombreVulgar1() {
        return this.nombreVulgar1;
    }
    
    public void setNombreVulgar1(String nombreVulgar1) {
        this.nombreVulgar1 = nombreVulgar1;
    }
    public String getNombreVulgar2() {
        return this.nombreVulgar2;
    }
    
    public void setNombreVulgar2(String nombreVulgar2) {
        this.nombreVulgar2 = nombreVulgar2;
    }
    public String getNombreVulgar3() {
        return this.nombreVulgar3;
    }
    
    public void setNombreVulgar3(String nombreVulgar3) {
        this.nombreVulgar3 = nombreVulgar3;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getColectas() {
        return this.colectas;
    }
    
    public void setColectas(Set colectas) {
        this.colectas = colectas;
    }




}


