package org.jgc.herbarium.be;
// Generated 03/10/2016 12:07:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Formacion generated by hbm2java
 */
@Component
public class Formacion  implements java.io.Serializable {


     private Long idformacion;
     private String formacionVegetal;
     private Boolean estado;
     private Set colectas = new HashSet(0);

    public Formacion() {
    }

    public Formacion(String formacionVegetal, Boolean estado, Set colectas) {
       this.formacionVegetal = formacionVegetal;
       this.estado = estado;
       this.colectas = colectas;
    }
   
    public Long getIdformacion() {
        return this.idformacion;
    }
    
    public void setIdformacion(Long idformacion) {
        this.idformacion = idformacion;
    }
    public String getFormacionVegetal() {
        return this.formacionVegetal;
    }
    
    public void setFormacionVegetal(String formacionVegetal) {
        this.formacionVegetal = formacionVegetal;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getColectas() {
        return this.colectas;
    }
    
    public void setColectas(Set colectas) {
        this.colectas = colectas;
    }




}


