package org.jgc.herbarium.be;
// Generated 03/10/2016 12:07:52 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * Fotografia generated by hbm2java
 */
@Component
public class Fotografia  implements java.io.Serializable {


     private Long idfotografia;
     private Colecta colecta;
     private Persona persona;
     private byte[] fotografia;
     private String descripcion;
     private String observacion;
     private Boolean estado;

    public Fotografia() {
    }

	
    public Fotografia(Colecta colecta) {
        this.colecta = colecta;
    }
    public Fotografia(Colecta colecta, Persona persona, byte[] fotografia, String descripcion, String observacion, Boolean estado) {
       this.colecta = colecta;
       this.persona = persona;
       this.fotografia = fotografia;
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.estado = estado;
    }
   
    public Long getIdfotografia() {
        return this.idfotografia;
    }
    
    public void setIdfotografia(Long idfotografia) {
        this.idfotografia = idfotografia;
    }
    public Colecta getColecta() {
        return this.colecta;
    }
    
    public void setColecta(Colecta colecta) {
        this.colecta = colecta;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public byte[] getFotografia() {
        return this.fotografia;
    }
    
    public void setFotografia(byte[] fotografia) {
        this.fotografia = fotografia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


