package org.jgc.herbarium.be;
// Generated 03/10/2016 12:07:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Gabinete generated by hbm2java
 */
@Component
public class Gabinete  implements java.io.Serializable {


     private Long idgabinete;
     private String nombre;
     private String codigo;
     private String descripcion;
     private Boolean estado;
     private Set casilleros = new HashSet(0);

    public Gabinete() {
    }

    public Gabinete(String nombre, String codigo, String descripcion, Boolean estado, Set casilleros) {
       this.nombre = nombre;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.estado = estado;
       this.casilleros = casilleros;
    }
   
    public Long getIdgabinete() {
        return this.idgabinete;
    }
    
    public void setIdgabinete(Long idgabinete) {
        this.idgabinete = idgabinete;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getCasilleros() {
        return this.casilleros;
    }
    
    public void setCasilleros(Set casilleros) {
        this.casilleros = casilleros;
    }




}


