package org.jgc.herbarium.be;
// Generated 03/10/2016 12:07:52 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * Imagen generated by hbm2java
 */
@Component
public class Imagen  implements java.io.Serializable {


     private Long idimagen;
     private Ejemplar ejemplar;
     private byte[] imagenOriginal;
     private byte[] imagenReducido;
     private String descripcion;
     private String observacion;

    public Imagen() {
    }

	
    public Imagen(Ejemplar ejemplar) {
        this.ejemplar = ejemplar;
    }
    public Imagen(Ejemplar ejemplar, byte[] imagenOriginal, byte[] imagenReducido, String descripcion, String observacion) {
       this.ejemplar = ejemplar;
       this.imagenOriginal = imagenOriginal;
       this.imagenReducido = imagenReducido;
       this.descripcion = descripcion;
       this.observacion = observacion;
    }
   
    public Long getIdimagen() {
        return this.idimagen;
    }
    
    public void setIdimagen(Long idimagen) {
        this.idimagen = idimagen;
    }
    public Ejemplar getEjemplar() {
        return this.ejemplar;
    }
    
    public void setEjemplar(Ejemplar ejemplar) {
        this.ejemplar = ejemplar;
    }
    public byte[] getImagenOriginal() {
        return this.imagenOriginal;
    }
    
    public void setImagenOriginal(byte[] imagenOriginal) {
        this.imagenOriginal = imagenOriginal;
    }
    public byte[] getImagenReducido() {
        return this.imagenReducido;
    }
    
    public void setImagenReducido(byte[] imagenReducido) {
        this.imagenReducido = imagenReducido;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


