package org.jgc.herbarium.be;
// Generated 03/10/2016 12:07:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Persona generated by hbm2java
 */
@Component
public class Persona  implements java.io.Serializable {


     private Long idpersona;
     private String nombres;
     private String apPaterno;
     private String apMaterno;
     private String dni;
     private Boolean sexo;
     private String telefono;
     private String celular1;
     private String celular2;
     private String correo;
     private Boolean estado;
     private Set usuarios = new HashSet(0);
     private Set fotografias = new HashSet(0);
     private Set colectaPersonas = new HashSet(0);

    public Persona() {
    }

    public Persona(String nombres, String apPaterno, String apMaterno, String dni, Boolean sexo, String telefono, String celular1, String celular2, String correo, Boolean estado, Set usuarios, Set fotografias, Set colectaPersonas) {
       this.nombres = nombres;
       this.apPaterno = apPaterno;
       this.apMaterno = apMaterno;
       this.dni = dni;
       this.sexo = sexo;
       this.telefono = telefono;
       this.celular1 = celular1;
       this.celular2 = celular2;
       this.correo = correo;
       this.estado = estado;
       this.usuarios = usuarios;
       this.fotografias = fotografias;
       this.colectaPersonas = colectaPersonas;
    }
   
    public Long getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(Long idpersona) {
        this.idpersona = idpersona;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApPaterno() {
        return this.apPaterno;
    }
    
    public void setApPaterno(String apPaterno) {
        this.apPaterno = apPaterno;
    }
    public String getApMaterno() {
        return this.apMaterno;
    }
    
    public void setApMaterno(String apMaterno) {
        this.apMaterno = apMaterno;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Boolean getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Boolean sexo) {
        this.sexo = sexo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular1() {
        return this.celular1;
    }
    
    public void setCelular1(String celular1) {
        this.celular1 = celular1;
    }
    public String getCelular2() {
        return this.celular2;
    }
    
    public void setCelular2(String celular2) {
        this.celular2 = celular2;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getFotografias() {
        return this.fotografias;
    }
    
    public void setFotografias(Set fotografias) {
        this.fotografias = fotografias;
    }
    public Set getColectaPersonas() {
        return this.colectaPersonas;
    }
    
    public void setColectaPersonas(Set colectaPersonas) {
        this.colectaPersonas = colectaPersonas;
    }




}


