package org.jgc.herbarium.be;
// Generated 03/10/2016 12:07:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Provincia generated by hbm2java
 */
@Component
public class Provincia  implements java.io.Serializable {


     private Long idprovincia;
     private Departamento departamento;
     private Integer codProvincia;
     private String denominacion;
     private Set distritos = new HashSet(0);

    public Provincia() {
        this.idprovincia = null;
        this.departamento = new Departamento();
    }

	
    public Provincia(Departamento departamento) {
        this.departamento = departamento;
    }
    public Provincia(Departamento departamento, Integer codProvincia, String denominacion, Set distritos) {
       this.departamento = departamento;
       this.codProvincia = codProvincia;
       this.denominacion = denominacion;
       this.distritos = distritos;
    }
   
    public Long getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(Long idprovincia) {
        this.idprovincia = idprovincia;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Integer getCodProvincia() {
        return this.codProvincia;
    }
    
    public void setCodProvincia(Integer codProvincia) {
        this.codProvincia = codProvincia;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public Set getDistritos() {
        return this.distritos;
    }
    
    public void setDistritos(Set distritos) {
        this.distritos = distritos;
    }




}


