package org.jgc.herbarium.be;
// Generated 03/10/2016 12:07:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Rol generated by hbm2java
 */
@Component
public class Rol  implements java.io.Serializable {


     private Long idrol;
     private String nombreRol;
     private String descripcion;
     private Boolean estado;
     private Set usuarioRols = new HashSet(0);

    public Rol() {
    }

    public Rol(String nombreRol, String descripcion, Boolean estado, Set usuarioRols) {
       this.nombreRol = nombreRol;
       this.descripcion = descripcion;
       this.estado = estado;
       this.usuarioRols = usuarioRols;
    }
   
    public Long getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(Long idrol) {
        this.idrol = idrol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set usuarioRols) {
        this.usuarioRols = usuarioRols;
    }




}


