package org.jgc.herbarium.be;
// Generated 03/10/2016 12:07:52 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * UsuarioRol generated by hbm2java
 */
@Component
public class UsuarioRol  implements java.io.Serializable {


     private Long idusuariorol;
     private Rol rol;
     private Usuario usuario;

    public UsuarioRol() {
    }

    public UsuarioRol(Rol rol, Usuario usuario) {
       this.rol = rol;
       this.usuario = usuario;
    }
   
    public Long getIdusuariorol() {
        return this.idusuariorol;
    }
    
    public void setIdusuariorol(Long idusuariorol) {
        this.idusuariorol = idusuariorol;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


